### ISSUE TITLE
Create a pip package for the tool

### ISSUE THREAD

**Issue by mattaereal** [shortdoom/gh-fake-analyzer#10]
I'd like to include it on a repo that holds a lot of tools, and this one is the only one that I have to troubleshoot a little bit in order to work seamlessly at the dockerfile.

**Comment by shortdoom** [comment]
@mattaereal 

I can't DM you on Twitter unfortunately, so pinging here.

I merged some new changes and those slightly change the structure of the output. In place of a multiple json files, we now get a single `report.json` with all of the data, there's also more compact formatting for nested fields. If you were integrating the old structure into some other pipelines, you'll need to make updates.

https://github.com/shortdoom/gh-fake-analyzer/pull/12

Now, I'll add the `pip` support. If there's anything else you'd like included that helps you out, feel free to open another Issue.

**Comment by mattaereal** [comment]
Not for now, haven't vastly explored it yet, only test cases to make sure it works as intended. Thanks!

**Comment by shortdoom** [comment]
@mattaereal 

I added pip support to `main`, it should now work from any directory, everywhere, feel free to give it a spin. PyPi package on the next iteration maybe (there're still some things I'd like to add before).

**Comment by shortdoom** [comment]
Nah, I need to update that part too. It still references the old report.json schema, additionally we profiled more types of malicious accounts with other metrics than mentioned.

Will fix it for PyPI release.

**Comment by mattaereal** [comment]
I will present @theredguild/devsecops-toolkit with your tool inside at devcon, so if you manage to create web3 related examples and a PyPi package, you'll get a nice opportunity

**Comment by shortdoom** [comment]
That's awesome. Yeah, elevating that to top priority. Will do before the 9th Nov.

**Comment by mattaereal** [comment]
Let me know as soon as you update everything since I'd like to have this ready way earlier. But don't want to rush you...

**Comment by shortdoom** [comment]
Of course. I'll try to knock-it down within a week, that should give you enough of a time.

**Comment by shortdoom** [comment]
@mattaereal 

Sorry for a delay.

`main` branch is now up to date with [pypi package](https://pypi.org/project/gh-fake-analyzer/), you can try installing with `pip install gh-fake-analyzer`. if you encounter any error, please open the issue, there were quite a few discrepancies I needed to patch between the development and pypi package and something could slip.

I also updated [Malicious Github Accounts](https://github.com/shortdoom/gh-fake-analyzer?tab=readme-ov-file#malicious-github-accounts) and [examples of web3-related attackers](https://github.com/shortdoom/gh-fake-analyzer?tab=readme-ov-file#regular-skidmaas-and-dprk-style-profile) sections.

If you want some additional context/q&a, hit me up on twitter.

**Comment by mattaereal** [comment]
dõmo arigatõ!
